# Generated by Django 4.2.3 on 2023-08-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('age', models.IntegerField(default=10)),
                ('kurs', models.CharField(max_length=20)),
                ('oqituvchisi', models.CharField(max_length=20)),
                ('discription', models.TextField(max_length=1000)),
                ('tel_nomer', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('github', models.URLField()),
                ('avatar', models.ImageField(upload_to='images/avatar')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
