# Generated by Django 4.2.3 on 2023-08-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_profilemodel_delete_usermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
