# Generated by Django 4.2.3 on 2023-08-29 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_profilemodel_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='avatar',
        ),
    ]
