# Generated by Django 4.2.1 on 2023-09-05 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_remove_profilemodel_tel_nomer_profilemodel_tnomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='kurs',
            field=models.CharField(choices=[('frontend', 'frontend'), ('backend', 'backend')], max_length=20),
        ),
    ]
