# Generated by Django 4.2.1 on 2023-09-05 15:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_profilemodel_profileid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='profileID',
            field=models.UUIDField(default=uuid.UUID('603a509a-fe18-4aef-88f7-03cfc99089d0'), primary_key=True, serialize=False),
        ),
    ]
