# Generated by Django 4.2.1 on 2023-09-07 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_profilemodel_profileid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileModel',
        ),
    ]
