# Generated by Django 4.2.1 on 2023-09-07 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0012_delete_profilemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150)),
                ('tel_N', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('project_image', models.ImageField(upload_to='images/')),
                ('profle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.profilem')),
            ],
        ),
    ]
