# Generated by Django 4.2.3 on 2023-09-07 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0015_remove_projectm_profle_delete_profilem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('tel_nomer', models.IntegerField()),
                ('date_cleaned', models.DateTimeField(auto_now_add=True)),
                ('profile_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('date_cleaned', models.DateTimeField(auto_now_add=True)),
                ('project_image', models.ImageField(upload_to='profileimg/')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.profilemodel')),
            ],
        ),
    ]
