# Generated by Django 4.2.3 on 2023-09-07 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='profile_image',
        ),
    ]
