# Generated by Django 4.2.3 on 2023-09-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_remove_projectmodel_profile_projectmodel_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tel_nomer',
            field=models.IntegerField(default=998),
        ),
    ]
