# Generated by Django 4.2.3 on 2023-09-09 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_profile_tel_nomer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
