# Generated by Django 4.2.3 on 2023-09-14 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
