# Generated by Django 4.2.3 on 2023-09-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='github_link',
            field=models.CharField(default='github-url', max_length=500),
        ),
    ]
