# Generated by Django 4.2.3 on 2023-09-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_projectmodel_github_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='project_image',
            field=models.ImageField(upload_to='projectImage/'),
        ),
    ]
