# Generated by Django 4.2.3 on 2023-09-23 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_projectmodel_profiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmodel',
            name='profiles',
        ),
        migrations.AddField(
            model_name='profile',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.projectmodel'),
        ),
    ]
