# Generated by Django 4.2.3 on 2023-09-26 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_projectmodel_yonalish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='profiles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.profile'),
        ),
    ]
