# Generated by Django 4.2.3 on 2023-10-07 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_commentmodel_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='user_profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='comment_user_images/'),
        ),
    ]
